Added hrmpWrapper helper function and added support for xcmTransactor.hrmpManage extrinsic
PureStake/xcm-tools pull request #59
Opened 2023-02-21 01:42 UTC by jboetticher

Changes: 

- When using the `hrmp-channel-manipulator.ts` script on networks using the `xcm-transactor` pallet, the extrinsic used will now be `xcmTransactor.hrmpManage` instead of the `polkadot-xcm.send` extrinsic
- Extrinsic construction within `hrmp-channel-manipulator.ts` has been moved to the `hrmpWrapper` function within `function-helpers.ts`
- Small fix to allow use of `hrmp-channel-manipulator.ts` on networks without governance

When using the script to open a channel on Moonbase Alpha, I received the following encoded call data:
```
0x210900e9030000e80300000090010000018080778c30c20fa2ebc0ed18d2cbca1f000010a5d4e800000000
```

2023-02-21 08:15 UTC, girazoki approved these changes

2023-02-21 15:45 UTC, albertov19 requested changes
Looks good! Couple of suggestions:

Maybe add the optional flag for fee asset and use the Multilocation way so that is more generic for other parachains to use.

Also (optional) move this functions out of the function helper file so that it is not too overloaded!

2023-02-22 16:48 UTC, albertov19 approved these changes
LGTM

2023-02-22 18:53 UTC, albertov19 approved these changes

2023-02-23 10:15 UTC, merged