Simplified para-registrar-swap
PureStake/xcm-tools pull request #66
Opened 2023-03-06 22:25 UTC by jboetticher

Replaced sections with the wrappers

2023-03-07 23:17 UTC, albertov19 commented
Hey @jboetticher this is still not following the sort of guidelines from the other scripts. Check https://github.com/PureStake/xcm-tools/blob/main/scripts/generic-call-proposer.ts#L47-L95 as an example

2023-03-10 16:25 UTC, albertov19 requested changes
Missing Gov V2 support 😬

2023-03-10 16:25 UTC, albertov19 commented on scripts/para-registrar-swapper.ts
> +            collectiveThreshold
We need to add support for Gov V2 here right?

2023-03-14 14:36 UTC, jboetticher commented
Well, I rebased to get OpenGovV2 changes into this branch. Not sure if that was the right git action, but it is what it is. Main changes are README & para-registrar-swapper.ts.

2023-03-14 14:41 UTC, albertov19 approved these changes
LGTM

2023-03-14 14:41 UTC, merged